### ISSUE TITLE
Tossed salads don't work and burgers...

### ISSUE THREAD

**Issue by tomixcomics** [Aurorastation/Aurora-Old#374]
I tried twice, with the right ingredients. was a burnt mess. 
And the bay wiki says to combine buns and meat to form a hamburger, but the "perfect" hamburger comes from microwaving the two, not combining.

**Comment by skull132** [comment]
Tossed salad - changelog indicates removal from recipes on 27AUG2014, by Soundscopes. Most likely due to an incomplete port of Baystation's cooking system. Not a bug straight-up, more of a discrephency between codebases.

Albeit, it is understandibly better to have our own recipe list as a result, or (preferably, for the time being) ensure we match Bay's.

To Scopes: there ain't much sillyness they can do with cooking, so something to look into?

**Comment by skull132** [comment]
@SoundScopes Mind if I take this one? Want to run some more cleanup on a few bugs noted over the week, and have already touched places where this one is in the last update.

**Comment by Jamini** [comment]
Salads are in the oven object now, and you can add in ingredients like most of the newer food items. I'm not sure this is really a bug, just a change in how that particular object functions?

**Comment by tomixcomics** [comment]
the salads you can make via the oven are completely different items.
first of all they don't include the same ingredients, and there's only so
many you can add.
secondly, they show up in these neon colors
and thirdly i don't use the new one-click machines because i feel like
making food items via a one-click machine instead of actually cooking them
the usual way is sort of "cheating" and takes what little challenge there
is to being a chef out of the game.
