### ISSUE TITLE
Duty Officers can bypass respawn timers

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#640]
DOfficer: SierraKomodo/(new player): I think I just accidentally found a way to bypass the respawn timer as a DO..
DOfficer: NursieKitty/(Phoebe Essel): share with the class
DOfficer: SierraKomodo/(new player): I ghosted at the 35 or so minute mark. A few minutes ago, I spawned as a DO to try out the newsfeed thing
DOfficer: SierraKomodo/(new player): Returned to mob, his respawn just to see exactly how much time I have, and it says I was dead for the entire round instead of since 35 or so
DOfficer: SierraKomodo/(new player): Sooooo.. That was odd.

**Comment by Sgtsammac** [comment]
Ehh. I don't think this needs to be a priority. I think if anything it's done on purpose to let you get back into the game.

Besides you are duty officers. You are trusted not to abuse it.

**Comment by OneOneThreeEight** [comment]
You should really forward these (as in, DO mechanical things) to Scopes himself like he's asked multiple times, Sierra.

**Comment by skull132** [comment]
Consider: @soundscopes sees these normally, so it's fine. Also, it's a
byproduct of the dead since var not being carried over from ghost to mob to
ghost.

**Comment by SoundScopes** [comment]
It's not intentional, there are multiple mechanics made to make sure they can get back in the round including a holder that keeps track of their old mob and a verb to put them back in incase they need to spawn in and can't or are not going to be gone long enough for cryo to work.

It's also not a priority unless someone is caught doing that which will be identifiable by logs.
