### ISSUE TITLE
Tajaran/Unathi tails use the wrong color

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora-Old#676]
Tajaran and Unathi tails are using the color value from the set hair instead of the body like they used to; This appears to have changed with the IPC update. A good example would be Sslazhir Yinzr, who has gone from having a green tail matching his scales, to having a black tail that matches his horns.

UPDATE: This appears to only be affecting the sprite preview on character creation, and the ghost sprite if you click observe. The in game sprite if you join around uses the correct color for the tail.

**Comment by SierraKomodo** [comment]
UPDATE: This appears to only be affecting the sprite preview on character creation, and the ghost sprite if you click observe. The in game sprite if you join around uses the correct color for the tail.

**Comment by Zuhayr** [comment]
The tail icon defaults to black (due to additive colouring), would be worth checking if it's actually using the hair colour or just not applying a colour at all.

Fixing icon generation code was hard enough that we just scrapped it and replaced it entirely with a dummy human mob in nullspace that updates based on prefs. Might be worth considering the same.
